#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-adephylo
Version  : 1.1.17
Release  : 54
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/adephylo_1.1-17.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/adephylo_1.1-17.tar.gz
Summary  : Exploratory Analyses for the Phylogenetic Comparative Method
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-adephylo-lib = %{version}-%{release}
Requires: R-ade4
Requires: R-adegenet
Requires: R-ape
Requires: R-phylobase
BuildRequires : R-ade4
BuildRequires : R-adegenet
BuildRequires : R-ape
BuildRequires : R-phylobase
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-adephylo package.
Group: Libraries

%description lib
lib components for the R-adephylo package.


%prep
%setup -q -n adephylo
pushd ..
cp -a adephylo buildavx2
popd
pushd ..
cp -a adephylo buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742467202

%install
export SOURCE_DATE_EPOCH=1742467202
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/adephylo/CITATION
/usr/lib64/R/library/adephylo/DESCRIPTION
/usr/lib64/R/library/adephylo/INDEX
/usr/lib64/R/library/adephylo/Meta/Rd.rds
/usr/lib64/R/library/adephylo/Meta/data.rds
/usr/lib64/R/library/adephylo/Meta/features.rds
/usr/lib64/R/library/adephylo/Meta/hsearch.rds
/usr/lib64/R/library/adephylo/Meta/links.rds
/usr/lib64/R/library/adephylo/Meta/nsInfo.rds
/usr/lib64/R/library/adephylo/Meta/package.rds
/usr/lib64/R/library/adephylo/Meta/vignette.rds
/usr/lib64/R/library/adephylo/NAMESPACE
/usr/lib64/R/library/adephylo/R/adephylo
/usr/lib64/R/library/adephylo/R/adephylo.rdb
/usr/lib64/R/library/adephylo/R/adephylo.rdx
/usr/lib64/R/library/adephylo/WORDLIST
/usr/lib64/R/library/adephylo/data/carni19.RData
/usr/lib64/R/library/adephylo/data/carni70.RData
/usr/lib64/R/library/adephylo/data/lizards.RData
/usr/lib64/R/library/adephylo/data/maples.RData
/usr/lib64/R/library/adephylo/data/mjrochet.RData
/usr/lib64/R/library/adephylo/data/palm.RData
/usr/lib64/R/library/adephylo/data/procella.RData
/usr/lib64/R/library/adephylo/data/tithonia.RData
/usr/lib64/R/library/adephylo/data/ungulates.RData
/usr/lib64/R/library/adephylo/doc/adephylo.R
/usr/lib64/R/library/adephylo/doc/adephylo.Rnw
/usr/lib64/R/library/adephylo/doc/adephylo.pdf
/usr/lib64/R/library/adephylo/doc/index.html
/usr/lib64/R/library/adephylo/help/AnIndex
/usr/lib64/R/library/adephylo/help/adephylo.rdb
/usr/lib64/R/library/adephylo/help/adephylo.rdx
/usr/lib64/R/library/adephylo/help/aliases.rds
/usr/lib64/R/library/adephylo/help/paths.rds
/usr/lib64/R/library/adephylo/html/00Index.html
/usr/lib64/R/library/adephylo/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/adephylo/libs/adephylo.so
/V4/usr/lib64/R/library/adephylo/libs/adephylo.so
/usr/lib64/R/library/adephylo/libs/adephylo.so
